# ========== 阿里云 OSS 配置 ==========
oss.endpoint=xxx
oss.accessKeyId=xx
oss.accessKeySecret=xxx
oss.bucketName=xx

# 静态域名（用于生成公开访问 URL）
oss.staticDomain=xxx

# OSS 上的根目录前缀（比如 ossfile/）
oss.rootPrefix=test